### PR TITLE
Template tagging and login added.

### PR DESCRIPTION
**Pull request by code-xD**

### CODE REVIEW

**Comment by code-xD** [comment]
@abhishekspeer @aarjavjain1 @coderjedi requirements.txt added

**Comment by code-xD** [comment]
@abhishekspeer @aarjavjain1 login functionality added and templates also added.

**Comment by code-xD** [comment]
Logout issue solved.

**Comment by code-xD** [comment]
@abhishekspeer @aarjavjain1 @coderjedi Template tagging completed JSON needs to be added.

**Review by aarjavjain1 — APPROVED** [review]

**Pull request closed without merging**
